// AUTO-GENERATED by scripts/export-board-art.mjs — do not edit by hand.
// Content hash of every exported board.svg + front.png + back.png. BoardArt
// appends it as ?v= to bust Oxygen's 1-year immutable asset cache when board
// art is regenerated in place.
export const BOARD_ART_VERSION = '54b028ba9b47';
