// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {providers} from '../models';

export function AutoScan():Promise<main.ScanResult>;

export function CheckAutostart():Promise<boolean>;

export function GetEngines():Promise<Array<string>>;

export function GetLogs():Promise<Array<string>>;

export function GetProfiles(arg1:string):Promise<Array<string>>;

export function GetStatus():Promise<providers.Status>;

export function LoadConfig():Promise<main.Settings>;

export function SaveConfig(arg1:string,arg2:string):Promise<void>;

export function ToggleAutostart(arg1:boolean):Promise<string>;

export function ToggleEngine(arg1:boolean,arg2:string,arg3:string):Promise<string>;
