// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoScan() {
  return window['go']['main']['App']['AutoScan']();
}

export function CheckAutostart() {
  return window['go']['main']['App']['CheckAutostart']();
}

export function GetEngines() {
  return window['go']['main']['App']['GetEngines']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetProfiles(arg1) {
  return window['go']['main']['App']['GetProfiles'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}

export function ToggleAutostart(arg1) {
  return window['go']['main']['App']['ToggleAutostart'](arg1);
}

export function ToggleEngine(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleEngine'](arg1, arg2, arg3);
}
