// AUTO-GENERATED by scripts/sync_modes.py — do not edit manually.
// Source of truth: backend/constants.py

export type ModeCategory = 'manual' | 'assisted' | 'auto' | 'emergency';
export type VehicleType = 'copter' | 'plane' | 'rover' | 'sub';

export interface ModeEntry {
  en: string;
  zh: string;
  category: ModeCategory;
}

export const MODE_TABLES: Record<VehicleType, Record<number, ModeEntry>> = {
  copter: {
    0: { en: 'Stabilize', zh: '自稳', category: 'manual' },
    1: { en: 'Acro', zh: '特技', category: 'manual' },
    2: { en: 'Alt Hold', zh: '定高', category: 'assisted' },
    3: { en: 'Auto', zh: '自动', category: 'auto' },
    4: { en: 'Guided', zh: '引导', category: 'auto' },
    5: { en: 'Loiter', zh: '悬停', category: 'assisted' },
    6: { en: 'RTL', zh: '返航', category: 'emergency' },
    7: { en: 'Circle', zh: '绕圈', category: 'auto' },
    9: { en: 'Land', zh: '降落', category: 'emergency' },
    11: { en: 'Drift', zh: '漂移', category: 'assisted' },
    13: { en: 'Sport', zh: '运动', category: 'manual' },
    14: { en: 'Flip', zh: '翻转', category: 'manual' },
    15: { en: 'AutoTune', zh: '自动调参', category: 'assisted' },
    16: { en: 'PosHold', zh: '定点', category: 'assisted' },
    17: { en: 'Brake', zh: '刹停', category: 'emergency' },
    18: { en: 'Throw', zh: '抛飞', category: 'auto' },
    19: { en: 'AvoidADSB', zh: '避障', category: 'emergency' },
    20: { en: 'GuidedNoGPS', zh: '引导无导航', category: 'auto' },
    21: { en: 'Smart RTL', zh: '智能返航', category: 'emergency' },
    22: { en: 'FlowHold', zh: '光流定点', category: 'assisted' },
    23: { en: 'Follow', zh: '跟随', category: 'assisted' },
    24: { en: 'ZigZag', zh: '蛇形', category: 'assisted' },
    25: { en: 'SystemID', zh: '系统辨识', category: 'auto' },
    26: { en: 'Autorotate', zh: '自旋下降', category: 'emergency' },
    27: { en: 'Auto RTL', zh: '自动返航', category: 'emergency' },
    28: { en: 'Turtle', zh: '翻龟', category: 'emergency' },
  },
  plane: {
    0: { en: 'Manual', zh: '手动', category: 'manual' },
    1: { en: 'Circle', zh: '绕圈', category: 'auto' },
    2: { en: 'Stabilize', zh: '自稳', category: 'manual' },
    3: { en: 'Training', zh: '训练', category: 'manual' },
    4: { en: 'Acro', zh: '特技', category: 'manual' },
    5: { en: 'FBW-A', zh: '辅助A', category: 'assisted' },
    6: { en: 'FBW-B', zh: '辅助B', category: 'assisted' },
    7: { en: 'Cruise', zh: '巡航', category: 'assisted' },
    8: { en: 'AutoTune', zh: '自动调参', category: 'assisted' },
    10: { en: 'Auto', zh: '自动', category: 'auto' },
    11: { en: 'RTL', zh: '返航', category: 'emergency' },
    12: { en: 'Loiter', zh: '盘旋', category: 'assisted' },
    13: { en: 'Takeoff', zh: '起飞', category: 'auto' },
    14: { en: 'AvoidADSB', zh: '自动避让', category: 'emergency' },
    15: { en: 'Guided', zh: '引导', category: 'auto' },
    16: { en: 'Initialising', zh: '初始化', category: 'auto' },
    17: { en: 'Q-Stabilize', zh: '旋翼自稳', category: 'manual' },
    18: { en: 'Q-Hover', zh: '旋翼悬停', category: 'assisted' },
    19: { en: 'Q-Loiter', zh: '旋翼定点', category: 'assisted' },
    20: { en: 'Q-Land', zh: '旋翼降落', category: 'emergency' },
    21: { en: 'Q-RTL', zh: '旋翼返航', category: 'emergency' },
    22: { en: 'QAutoTune', zh: '旋翼自调', category: 'assisted' },
    23: { en: 'QAcro', zh: '旋翼特技', category: 'manual' },
    24: { en: 'Thermal', zh: '热气流', category: 'assisted' },
    25: { en: 'Loiter2QLand', zh: '盘旋至定点', category: 'emergency' },
    26: { en: 'Autoland', zh: '自动着陆', category: 'emergency' },
  },
  rover: {
    0: { en: 'Manual', zh: '手动', category: 'manual' },
    1: { en: 'Acro', zh: '特技', category: 'manual' },
    3: { en: 'Steering', zh: '转向', category: 'assisted' },
    4: { en: 'Hold', zh: '固定', category: 'assisted' },
    5: { en: 'Loiter', zh: '悬停', category: 'assisted' },
    6: { en: 'Follow', zh: '跟随', category: 'auto' },
    7: { en: 'Simple', zh: '简单', category: 'assisted' },
    8: { en: 'Dock', zh: '停靠', category: 'auto' },
    9: { en: 'Circle', zh: '环线', category: 'auto' },
    10: { en: 'Auto', zh: '自动', category: 'auto' },
    11: { en: 'RTL', zh: '返航', category: 'emergency' },
    12: { en: 'Smart RTL', zh: '智能返航', category: 'emergency' },
    15: { en: 'Guided', zh: '引导', category: 'auto' },
    16: { en: 'Initialising', zh: '初始化', category: 'auto' },
  },
  sub: {
    0: { en: 'Stabilize', zh: '自稳', category: 'manual' },
    1: { en: 'Acro', zh: '特技', category: 'manual' },
    2: { en: 'Depth Hold', zh: '定深', category: 'assisted' },
    3: { en: 'Auto', zh: '自动', category: 'auto' },
    4: { en: 'Guided', zh: '引导', category: 'auto' },
    7: { en: 'Circle', zh: '绕圈', category: 'auto' },
    9: { en: 'Surface', zh: '水面', category: 'emergency' },
    16: { en: 'PosHold', zh: '定点', category: 'assisted' },
    19: { en: 'Manual', zh: '手动', category: 'manual' },
    20: { en: 'Motor Detect', zh: '电机检测', category: 'auto' },
    21: { en: 'Surftrak', zh: '地形跟随', category: 'assisted' },
  },
};

export const BTN_IDS: Record<VehicleType, number[]> = {
  copter: [0, 2, 5, 3, 6, 9],
  plane: [0, 10, 11, 12, 19, 18, 17, 21, 20],
  rover: [0, 4, 10, 15, 11],
  sub: [0, 2, 16, 3, 4],
};

const _VTYPE_MAP: Record<number, VehicleType> = {
  2: 'copter',
  3: 'copter',
  4: 'copter',
  13: 'copter',
  14: 'copter',
  1: 'plane',
  19: 'plane',
  20: 'plane',
  21: 'plane',
  22: 'plane',
  23: 'plane',
  24: 'plane',
  25: 'plane',
  10: 'rover',
  12: 'sub',
};

export function vehicleType(mavTypeRaw: number): VehicleType {
  return _VTYPE_MAP[mavTypeRaw] ?? 'copter';
}

export function getModeName(vtype: VehicleType, modeId: number, locale: 'en' | 'zh' = 'en'): string {
  return MODE_TABLES[vtype]?.[modeId]?.[locale] ?? `MODE${modeId}`;
}

export function getModeCategory(vtype: VehicleType, modeId: number): ModeCategory {
  return MODE_TABLES[vtype]?.[modeId]?.category ?? 'assisted';
}

export function getModeButtons(vtype: VehicleType, locale: 'en' | 'zh' = 'en'): [number, string][] {
  const ids = BTN_IDS[vtype] ?? [];
  return ids.map((id) => [id, getModeName(vtype, id, locale)]);
}

export function getAllModes(vtype: VehicleType): { id: number; name: string; category: ModeCategory }[] {
  const table = MODE_TABLES[vtype] ?? {};
  return Object.entries(table)
    .map(([id, m]) => ({ id: Number(id), name: m.en, category: m.category }))
    .sort((a, b) => a.id - b.id);
}

export function getModeEntries(vtype: VehicleType): [number, string][] {
  const table = MODE_TABLES[vtype] ?? {};
  return Object.entries(table)
    .map(([id, m]) => [Number(id), m.en] as [number, string])
    .sort((a, b) => a[0] - b[0]);
}

