/**
 * EGM96 geoid separation — the honest MSL <-> ellipsoidal-height boundary.
 *
 * GPS altitude is height above the WGS-84 ellipsoid; almost every operator-facing
 * altitude (Open-Elevation terrain, ArduPilot absolute-frame AMSL, a chart's MSL)
 * is orthometric — height above the geoid (mean sea level). The two differ by the
 * geoid undulation `N`, which swings roughly -107 m .. +85 m worldwide. Ignoring it
 * floats a Cesium-placed absolute-altitude path off the terrain by up to ~100 m.
 *
 * A bundled EGM96 undulation grid (`public/geoid/egm96-1deg.i16.gz`, Int16
 * centimetres, generated by `scripts/geoid/generate.mjs` from the public-domain
 * NGA/NASA `WW15MGH.GRD`) is fetched lazily and bilinearly sampled. Structure
 * mirrors the bundled parameter-metadata loader: fetch -> pako -> memory cache,
 * empty-on-miss, never throws.
 *
 * HONEST PASSTHROUGH: until the grid asset is loaded (or if it is absent),
 * `geoidSeparation` returns `NaN` and the conversions return their input
 * UNCHANGED. That is the "MSL-only-correct until the grid lands" rule — a missing
 * asset degrades to treating MSL as ellipsoidal (the prior behaviour), never to a
 * fabricated undulation.
 *
 * Applies ONLY to visualization placement (the Cesium 3D planned/flown path).
 * Mission-file export/import is deliberately NOT geoid-corrected: Open-Elevation
 * MSL and ArduPilot absolute-frame AMSL share the same orthometric datum, so
 * MSL<->AMSL is identity there and a geoid shift would corrupt a correct altitude.
 *
 * @module terrain/geoid
 * @license GPL-3.0-only
 */

import { ungzip } from "pako";

/** Bundled grid asset path (same-origin static file). */
const GRID_PATH = "/geoid/egm96-1deg.i16.gz";

/**
 * Grid geometry (1 deg). 361 columns (longitude 0..360 deg inclusive) x 181 rows
 * (latitude +90..-90 deg inclusive), row-major, corner origin at (+90, 0) with
 * latitude decreasing per row and longitude increasing per column. MUST match
 * `scripts/geoid/generate.mjs`.
 */
const NCOLS = 361;
const NROWS = 181;
const GRID_LEN = NCOLS * NROWS; // 65,341

/** Empty sentinel — a missing/unparsable asset caches this so lookups return NaN. */
const EMPTY = new Int16Array(0);

// Memory cache so the asset is fetched + parsed once per session. Null until the
// first load attempt; EMPTY (length 0) after a miss; a full grid after a hit.
let gridCache: Int16Array | null = null;
// Coalesces concurrent callers onto a single in-flight fetch.
let loadPromise: Promise<void> | null = null;

/**
 * Load the bundled EGM96 undulation grid. Always resolves (empty on miss),
 * NEVER throws. Idempotent + memory-cached; safe to call repeatedly and from
 * multiple mount points.
 */
export async function loadGeoidGrid(): Promise<void> {
  if (gridCache) return; // already loaded, or cached-empty after a miss
  if (loadPromise) return loadPromise;
  loadPromise = (async () => {
    try {
      const res = await fetch(GRID_PATH);
      if (!res.ok) {
        gridCache = EMPTY;
        return;
      }
      const bytes = ungzip(new Uint8Array(await res.arrayBuffer()));
      const count = Math.floor(bytes.byteLength / 2);
      if (count !== GRID_LEN) {
        // Wrong-sized asset — treat as absent rather than mis-index it.
        gridCache = EMPTY;
        return;
      }
      // Decode little-endian Int16 explicitly (endianness- and alignment-safe;
      // matches the Buffer.writeInt16LE the generator emits).
      const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
      const grid = new Int16Array(GRID_LEN);
      for (let i = 0; i < GRID_LEN; i++) grid[i] = view.getInt16(i * 2, true);
      gridCache = grid;
    } catch {
      // Missing file / decode error -> no geoid floor; stays NaN-passthrough.
      gridCache = EMPTY;
    }
  })();
  return loadPromise;
}

/**
 * EGM96 geoid separation `N` (metres) at a geographic point: the height of the
 * geoid above the WGS-84 ellipsoid. Positive where the geoid is above the
 * ellipsoid. Bilinearly interpolated over the bundled 1-deg grid.
 *
 * Returns `NaN` until the grid asset is loaded/available (call `loadGeoidGrid`).
 */
export function geoidSeparation(lat: number, lon: number): number {
  const grid = gridCache;
  if (!grid || grid.length !== GRID_LEN) return NaN;
  if (!Number.isFinite(lat) || !Number.isFinite(lon)) return NaN;

  // Latitude clamped to the grid; longitude normalized into [0, 360).
  const clampedLat = lat > 90 ? 90 : lat < -90 ? -90 : lat;
  const normLon = ((lon % 360) + 360) % 360;

  // Fractional grid coordinates. rowF: 0 at +90, 180 at -90. colF == longitude.
  const rowF = 90 - clampedLat; // [0, 180]
  const colF = normLon; // [0, 360)

  let r0 = Math.floor(rowF);
  if (r0 > NROWS - 2) r0 = NROWS - 2;
  if (r0 < 0) r0 = 0;
  const r1 = r0 + 1;
  const tr = rowF - r0;

  let c0 = Math.floor(colF);
  if (c0 > NCOLS - 2) c0 = NCOLS - 2;
  if (c0 < 0) c0 = 0;
  const c1 = c0 + 1;
  const tc = colF - c0;

  const v00 = grid[r0 * NCOLS + c0];
  const v01 = grid[r0 * NCOLS + c1];
  const v10 = grid[r1 * NCOLS + c0];
  const v11 = grid[r1 * NCOLS + c1];
  const top = v00 + (v01 - v00) * tc;
  const bot = v10 + (v11 - v10) * tc;
  return (top + (bot - top) * tr) / 100; // centimetres -> metres
}

/**
 * Convert an MSL/orthometric altitude to ellipsoidal height for Cesium placement:
 * `h = MSL + N`. When the grid is absent (`N` is NaN) the input is returned
 * UNCHANGED — the honest MSL-only-correct passthrough.
 */
export function mslToEllipsoidal(msl: number, lat: number, lon: number): number {
  const n = geoidSeparation(lat, lon);
  return Number.isNaN(n) ? msl : msl + n;
}

/**
 * Convert an ellipsoidal height back to MSL/orthometric: `MSL = h - N`. When the
 * grid is absent (`N` is NaN) the input is returned UNCHANGED.
 */
export function ellipsoidalToMsl(h: number, lat: number, lon: number): number {
  const n = geoidSeparation(lat, lon);
  return Number.isNaN(n) ? h : h - n;
}
