use std::path::{Path, PathBuf};
use tokio::process::Command;
use tokio::fs;
use std::collections::HashMap;

#[derive(Debug, Clone)]
pub struct BlackboxSummary {
    pub d_term_noise_roll: f64,
    pub d_term_noise_pitch: f64,
    pub d_term_noise_yaw: f64,
    pub max_gyro_roll: f64,
    pub max_gyro_pitch: f64,
    pub max_gyro_yaw: f64,
    pub oscillation_count: usize,
    pub total_samples: usize,
}

impl BlackboxSummary {
    pub fn to_text(&self) -> String {
        format!(
            r#"📊 BLACKBOX LOG ANALYSIS

D-TERM NOISE LEVELS:
• Roll:  {:.2} (lower is better)
• Pitch: {:.2} (lower is better)
• Yaw:   {:.2} (lower is better)

MAX GYRO PEAKS (deg/s):
• Roll:  {:.1}°/s
• Pitch: {:.1}°/s
• Yaw:   {:.1}°/s

OSCILLATIONS DETECTED: {} events
TOTAL SAMPLES: {}

RECOMMENDATIONS:
{}"#,
            self.d_term_noise_roll,
            self.d_term_noise_pitch,
            self.d_term_noise_yaw,
            self.max_gyro_roll,
            self.max_gyro_pitch,
            self.max_gyro_yaw,
            self.oscillation_count,
            self.total_samples,
            self.generate_recommendations()
        )
    }

    fn generate_recommendations(&self) -> String {
        let mut recs = Vec::new();

        if self.d_term_noise_roll > 50.0 || self.d_term_noise_pitch > 50.0 {
            recs.push("⚠️ High D-term noise detected. Consider lowering D gain or enabling D-term filtering.");
        }

        if self.max_gyro_roll > 1000.0 || self.max_gyro_pitch > 1000.0 {
            recs.push("⚠️ Extreme gyro peaks detected. Check for mechanical issues or prop balance.");
        }

        if self.oscillation_count > 100 {
            recs.push("⚠️ Multiple oscillations detected. Reduce P gain or increase D gain.");
        }

        if recs.is_empty() {
            recs.push("✅ Log looks clean. No major issues detected.");
        }

        recs.join("\n")
    }
}

pub struct BlackboxParser;

impl BlackboxParser {
    pub fn new() -> Self {
        Self
    }

    pub async fn decode_bbl(&self, bbl_path: &Path) -> Result<PathBuf, String> {
        let csv_path = bbl_path.with_extension("csv");

        let output = Command::new("blackbox_decode")
            .arg(bbl_path.to_str().unwrap())
            .output()
            .await
            .map_err(|e| format!("blackbox_decode not found or failed: {}", e))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(format!("blackbox_decode failed: {}", stderr));
        }

        if !csv_path.exists() {
            return Err("CSV file not generated by blackbox_decode".to_string());
        }

        log::info!("Decoded BBL to CSV: {:?}", csv_path);
        Ok(csv_path)
    }

    pub async fn analyze_csv(&self, csv_path: &Path) -> Result<BlackboxSummary, String> {
        let content = fs::read_to_string(csv_path)
            .await
            .map_err(|e| format!("Failed to read CSV: {}", e))?;

        let mut reader = csv::ReaderBuilder::new()
            .has_headers(true)
            .from_reader(content.as_bytes());

        let headers = reader.headers()
            .map_err(|e| format!("Failed to read CSV headers: {}", e))?
            .clone();

        let gyro_roll_idx = headers.iter().position(|h| h.contains("gyroADC[0]"));
        let gyro_pitch_idx = headers.iter().position(|h| h.contains("gyroADC[1]"));
        let gyro_yaw_idx = headers.iter().position(|h| h.contains("gyroADC[2]"));
        let debug0_idx = headers.iter().position(|h| h.contains("debug[0]"));
        let debug1_idx = headers.iter().position(|h| h.contains("debug[1]"));
        let debug2_idx = headers.iter().position(|h| h.contains("debug[2]"));

        let mut gyro_roll_values = Vec::new();
        let mut gyro_pitch_values = Vec::new();
        let mut gyro_yaw_values = Vec::new();
        let mut debug0_values = Vec::new();
        let mut debug1_values = Vec::new();
        let mut debug2_values = Vec::new();

        for result in reader.records() {
            let record = result.map_err(|e| format!("CSV parse error: {}", e))?;

            if let Some(idx) = gyro_roll_idx {
                if let Ok(val) = record.get(idx).unwrap_or("0").parse::<f64>() {
                    gyro_roll_values.push(val);
                }
            }
            if let Some(idx) = gyro_pitch_idx {
                if let Ok(val) = record.get(idx).unwrap_or("0").parse::<f64>() {
                    gyro_pitch_values.push(val);
                }
            }
            if let Some(idx) = gyro_yaw_idx {
                if let Ok(val) = record.get(idx).unwrap_or("0").parse::<f64>() {
                    gyro_yaw_values.push(val);
                }
            }
            if let Some(idx) = debug0_idx {
                if let Ok(val) = record.get(idx).unwrap_or("0").parse::<f64>() {
                    debug0_values.push(val);
                }
            }
            if let Some(idx) = debug1_idx {
                if let Ok(val) = record.get(idx).unwrap_or("0").parse::<f64>() {
                    debug1_values.push(val);
                }
            }
            if let Some(idx) = debug2_idx {
                if let Ok(val) = record.get(idx).unwrap_or("0").parse::<f64>() {
                    debug2_values.push(val);
                }
            }
        }

        let total_samples = gyro_roll_values.len();

        let d_term_noise_roll = Self::calculate_std_dev(&debug0_values);
        let d_term_noise_pitch = Self::calculate_std_dev(&debug1_values);
        let d_term_noise_yaw = Self::calculate_std_dev(&debug2_values);

        let max_gyro_roll = gyro_roll_values.iter().map(|v| v.abs()).fold(0.0, f64::max);
        let max_gyro_pitch = gyro_pitch_values.iter().map(|v| v.abs()).fold(0.0, f64::max);
        let max_gyro_yaw = gyro_yaw_values.iter().map(|v| v.abs()).fold(0.0, f64::max);

        let oscillation_count = Self::count_zero_crossings(&gyro_roll_values)
            + Self::count_zero_crossings(&gyro_pitch_values);

        Ok(BlackboxSummary {
            d_term_noise_roll,
            d_term_noise_pitch,
            d_term_noise_yaw,
            max_gyro_roll,
            max_gyro_pitch,
            max_gyro_yaw,
            oscillation_count,
            total_samples,
        })
    }

    fn calculate_std_dev(values: &[f64]) -> f64 {
        if values.is_empty() {
            return 0.0;
        }

        let mean = values.iter().sum::<f64>() / values.len() as f64;
        let variance = values.iter().map(|v| (v - mean).powi(2)).sum::<f64>() / values.len() as f64;
        variance.sqrt()
    }

    fn count_zero_crossings(values: &[f64]) -> usize {
        let mut count = 0;
        for i in 1..values.len() {
            if (values[i - 1] > 0.0 && values[i] < 0.0) || (values[i - 1] < 0.0 && values[i] > 0.0) {
                count += 1;
            }
        }
        count
    }

    pub async fn process_blackbox(&self, bbl_path: &Path) -> Result<String, String> {
        log::info!("Processing blackbox log: {:?}", bbl_path);

        let csv_path = self.decode_bbl(bbl_path).await?;
        let summary = self.analyze_csv(&csv_path).await?;

        fs::remove_file(&csv_path).await.ok();

        Ok(summary.to_text())
    }
}
