// Telegram Bot in HolyC  
// This bot responds to the /start command  
echo // Telegram Bot in HolyC > "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo // This bot responds to the /start command >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo. >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo U0 HandleStartCommand(I64 chat_id) { >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo   I64 message = "Hello! Welcome to the HolyC Telegram Bot. This bot is written in HolyC!"; >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo   Print("Sending message to chat %%%%%%d: %%%%%%s\\n", chat_id, message); >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo } >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo. >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo U0 ProcessMessage(I64 chat_id, I64 text) { >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo   if (text && !StrCmp(text, "/start")) {  // Compare strings for "/start" >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo     HandleStartCommand(chat_id); >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo   } else { >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo     Print("Received message: %%%%%%s\\n", text); >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo   } >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo } >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo. >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo U0 TelegramBotMain() { >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo   Print("Starting Telegram Bot...\\n"); >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo   Print("Bot is running. Send /start to get a response.\\n"); >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo. >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo   // Simulate receiving a /start command >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo   ProcessMessage(123456789, "/start"); >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo } >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo. >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo // Entry point >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo U0 main() { >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo   TelegramBotMain(); >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC"  
echo } >> "f:\Projects\HolyBot\TELEGRAM_BOT_FULL.HC" 
