/**
 * MAVLink CRC-16/MCRF4XX — X.25 variant used by MAVLink v2.
 *
 * Accumulate bytes into a running CRC, then finalize with the per-message
 * CRC_EXTRA seed to detect definition mismatches.
 */

export function crc16(data: Uint8Array, initial = 0xffff): number {
  let crc = initial;
  for (let i = 0; i < data.length; i++) {
    let tmp = (data[i] ^ (crc & 0xff)) & 0xff;
    tmp ^= (tmp << 4) & 0xff;
    crc = ((crc >> 8) ^ (tmp << 8) ^ (tmp << 3) ^ (tmp >> 4)) & 0xffff;
  }
  return crc;
}

export function crcAccumulate(byte: number, crc: number): number {
  let tmp = (byte ^ (crc & 0xff)) & 0xff;
  tmp ^= (tmp << 4) & 0xff;
  return ((crc >> 8) ^ (tmp << 8) ^ (tmp << 3) ^ (tmp >> 4)) & 0xffff;
}

/**
 * CRC_EXTRA values for common MAVLink messages.
 * AUTO-GENERATED by scripts/sync_crc.py — do not edit manually.
 * Source of truth: backend/crc_extras.py
 */
export const CRC_EXTRA: Record<number, number> = {
  0: 50, // HEARTBEAT
  1: 124, // SYS_STATUS
  2: 137, // SYSTEM_TIME
  4: 237, // PING
  11: 89, // SET_MODE
  20: 214, // PARAM_REQUEST_READ
  21: 159, // PARAM_REQUEST_LIST
  22: 220, // PARAM_VALUE
  23: 168, // PARAM_SET
  24: 24, // GPS_RAW_INT
  27: 144, // RAW_IMU
  29: 115, // SCALED_PRESSURE
  30: 39, // ATTITUDE
  33: 104, // GLOBAL_POSITION_INT
  35: 244, // RC_CHANNELS_RAW
  36: 222, // SERVO_OUTPUT_RAW
  39: 254, // MISSION_ITEM
  40: 230, // MISSION_REQUEST
  41: 28, // MISSION_SET_CURRENT
  42: 28, // MISSION_CURRENT
  43: 132, // MISSION_REQUEST_LIST
  44: 221, // MISSION_COUNT
  45: 232, // MISSION_CLEAR_ALL
  46: 11, // MISSION_ITEM_REACHED
  47: 153, // MISSION_ACK
  51: 196, // MISSION_REQUEST_INT
  65: 118, // RC_CHANNELS
  66: 148, // REQUEST_DATA_STREAM
  69: 243, // MANUAL_CONTROL
  70: 124, // RC_CHANNELS_OVERRIDE
  73: 38, // MISSION_ITEM_INT
  74: 20, // VFR_HUD
  75: 158, // COMMAND_INT
  76: 152, // COMMAND_LONG
  77: 143, // COMMAND_ACK
  83: 22, // ATTITUDE_TARGET
  85: 140, // POSITION_TARGET_LOCAL_NED
  86: 5, // SET_POSITION_TARGET_GLOBAL_INT
  87: 150, // POSITION_TARGET_GLOBAL_INT
  105: 93, // HIGHRES_IMU
  116: 76, // SCALED_IMU2
  117: 128, // LOG_REQUEST_LIST
  118: 56, // LOG_ENTRY
  119: 116, // LOG_REQUEST_DATA
  120: 134, // LOG_DATA
  122: 203, // LOG_REQUEST_END
  125: 203, // POWER_STATUS
  126: 220, // SERIAL_CONTROL
  136: 1, // TERRAIN_REPORT
  147: 154, // BATTERY_STATUS
  148: 178, // AUTOPILOT_VERSION
  158: 134, // MOUNT_STATUS
  163: 127, // AHRS
  168: 1, // WIND
  178: 47, // AHRS2
  191: 92, // MAG_CAL_PROGRESS
  192: 36, // MAG_CAL_REPORT
  193: 71, // EKF_STATUS_REPORT
  233: 35, // GPS_RTCM_DATA
  241: 90, // VIBRATION
  242: 104, // HOME_POSITION
  246: 184, // ADSB_VEHICLE
  253: 83, // STATUSTEXT
  285: 137, // GIMBAL_DEVICE_ATTITUDE_STATUS
  310: 28, // UAVCAN_NODE_STATUS
  311: 95, // UAVCAN_NODE_INFO
};
