<Project>
  <PropertyGroup>
    <AvaloniaVersion>11.3.14</AvaloniaVersion>
    <AvaloniaSvgSkiaVersion>11.3.0</AvaloniaSvgSkiaVersion>
    <AvaloniaXamlInteractivityVersion>11.3.0.6</AvaloniaXamlInteractivityVersion>
    <SkiaSharpNativeAssetsLinuxVersion>3.116.1</SkiaSharpNativeAssetsLinuxVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.10.91" PrivateAssets="all" />
  </ItemGroup>
</Project>
