#!/usr/bin/env python3
"""Generate the CRC_EXTRA table in src/lib/mavlink/crc.ts from backend/crc_extras.py.

Run after adding/changing CRC extras in crc_extras.py to keep the frontend
single source of truth in sync:

    python scripts/sync_crc.py

The generated section is checked in — no runtime dependency on the backend.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from backend.crc_extras import CRC_EXTRA  # noqa: E402

OUT = ROOT / "src" / "lib" / "mavlink" / "crc.ts"

# Message name comments — keep in sync with crc_extras.py for readability.
_MSG_NAMES: dict[int, str] = {
    0: "HEARTBEAT",
    1: "SYS_STATUS",
    2: "SYSTEM_TIME",
    4: "PING",
    11: "SET_MODE",
    20: "PARAM_REQUEST_READ",
    21: "PARAM_REQUEST_LIST",
    22: "PARAM_VALUE",
    23: "PARAM_SET",
    24: "GPS_RAW_INT",
    27: "RAW_IMU",
    29: "SCALED_PRESSURE",
    30: "ATTITUDE",
    33: "GLOBAL_POSITION_INT",
    35: "RC_CHANNELS_RAW",
    36: "SERVO_OUTPUT_RAW",
    39: "MISSION_ITEM",
    40: "MISSION_REQUEST",
    41: "MISSION_SET_CURRENT",
    42: "MISSION_CURRENT",
    43: "MISSION_REQUEST_LIST",
    44: "MISSION_COUNT",
    45: "MISSION_CLEAR_ALL",
    46: "MISSION_ITEM_REACHED",
    47: "MISSION_ACK",
    51: "MISSION_REQUEST_INT",
    65: "RC_CHANNELS",
    66: "REQUEST_DATA_STREAM",
    69: "MANUAL_CONTROL",
    70: "RC_CHANNELS_OVERRIDE",
    73: "MISSION_ITEM_INT",
    74: "VFR_HUD",
    75: "COMMAND_INT",
    76: "COMMAND_LONG",
    77: "COMMAND_ACK",
    83: "ATTITUDE_TARGET",
    85: "POSITION_TARGET_LOCAL_NED",
    86: "SET_POSITION_TARGET_GLOBAL_INT",
    87: "POSITION_TARGET_GLOBAL_INT",
    105: "HIGHRES_IMU",
    116: "SCALED_IMU2",
    117: "LOG_REQUEST_LIST",
    118: "LOG_ENTRY",
    119: "LOG_REQUEST_DATA",
    120: "LOG_DATA",
    122: "LOG_REQUEST_END",
    125: "POWER_STATUS",
    126: "SERIAL_CONTROL",
    136: "TERRAIN_REPORT",
    147: "BATTERY_STATUS",
    148: "AUTOPILOT_VERSION",
    158: "MOUNT_STATUS",
    163: "AHRS",
    168: "WIND",
    178: "AHRS2",
    191: "MAG_CAL_PROGRESS",
    192: "MAG_CAL_REPORT",
    193: "EKF_STATUS_REPORT",
    233: "GPS_RTCM_DATA",
    241: "VIBRATION",
    242: "HOME_POSITION",
    246: "ADSB_VEHICLE",
    253: "STATUSTEXT",
    285: "GIMBAL_DEVICE_ATTITUDE_STATUS",
    310: "UAVCAN_NODE_STATUS",
    311: "UAVCAN_NODE_INFO",
}


def _generate_table() -> str:
    """Build the CRC_EXTRA object literal from the canonical dict."""
    lines: list[str] = []
    for mid in sorted(CRC_EXTRA):
        name = _MSG_NAMES.get(mid, "")
        comment = f" // {name}" if name else ""
        lines.append(f"  {mid}: {CRC_EXTRA[mid]},{comment}")
    return "\n".join(lines)


def main() -> None:
    src = OUT.read_text(encoding="utf-8")

    # Replace the contents between the opening `{` and closing `};` of the
    # CRC_EXTRA record.  The regex matches the whole block.
    pattern = r"(export const CRC_EXTRA: Record<number, number> = \{)\n.*?\n(\};)"
    replacement = r"\1\n" + _generate_table() + r"\n\2"
    new_src, count = re.subn(pattern, replacement, src, flags=re.DOTALL)
    if count != 1:
        print("ERROR: could not find CRC_EXTRA block in %s" % OUT, file=sys.stderr)
        sys.exit(1)

    # Update the header comment to indicate generated source.
    new_src = new_src.replace(
        "Generated from the MAVLink XML definition files.",
        "AUTO-GENERATED by scripts/sync_crc.py — do not edit manually.\n * Source of truth: backend/crc_extras.py",
    )

    OUT.write_text(new_src, encoding="utf-8")
    print("Generated %s (%d entries)" % (OUT.relative_to(ROOT), len(CRC_EXTRA)))


if __name__ == "__main__":
    main()
