#!/usr/bin/env python3
"""Generate src/lib/modeStore.ts from backend/constants.py.

Run after adding/changing modes in constants.py to keep the frontend
single source of truth in sync:

    python scripts/sync_modes.py

The generated file is checked in — no runtime dependency on the backend.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from backend.constants import (  # noqa: E402
    COPTER_BTNS_EN,
    COPTER_CATEGORIES,
    COPTER_MODES,
    COPTER_MODES_EN,
    PLANE_BTNS_EN,
    PLANE_CATEGORIES,
    PLANE_MODES,
    PLANE_MODES_EN,
    ROVER_BTNS_EN,
    ROVER_CATEGORIES,
    ROVER_MODES,
    ROVER_MODES_EN,
    SUB_BTNS_EN,
    SUB_CATEGORIES,
    SUB_MODES,
    SUB_MODES_EN,
)

VEHICLE_DEFS = [
    ("copter", COPTER_MODES, COPTER_MODES_EN, COPTER_CATEGORIES, COPTER_BTNS_EN),
    ("plane", PLANE_MODES, PLANE_MODES_EN, PLANE_CATEGORIES, PLANE_BTNS_EN),
    ("rover", ROVER_MODES, ROVER_MODES_EN, ROVER_CATEGORIES, ROVER_BTNS_EN),
    ("sub", SUB_MODES, SUB_MODES_EN, SUB_CATEGORIES, SUB_BTNS_EN),
]

OUT = ROOT / "src" / "lib" / "modeStore.ts"


def q(s: str) -> str:
    return s.replace("'", "\\'")


def generate() -> str:
    lines: list[str] = []
    lines.append("// AUTO-GENERATED by scripts/sync_modes.py — do not edit manually.")
    lines.append("// Source of truth: backend/constants.py")
    lines.append("")
    lines.append("export type ModeCategory = 'manual' | 'assisted' | 'auto' | 'emergency';")
    lines.append("export type VehicleType = 'copter' | 'plane' | 'rover' | 'sub';")
    lines.append("")
    lines.append("export interface ModeEntry {")
    lines.append("  en: string;")
    lines.append("  zh: string;")
    lines.append("  category: ModeCategory;")
    lines.append("}")
    lines.append("")

    # Mode tables
    lines.append("export const MODE_TABLES: Record<VehicleType, Record<number, ModeEntry>> = {")
    for vtype, zh_map, en_map, cat_map, _ in VEHICLE_DEFS:
        lines.append(f"  {vtype}: {{")
        all_ids = sorted(set(en_map) | set(zh_map))
        for mid in all_ids:
            en = q(en_map.get(mid, f"Mode{mid}"))
            zh = q(zh_map.get(mid, en))
            cat = cat_map.get(mid, "assisted")
            lines.append(f"    {mid}: {{ en: '{en}', zh: '{zh}', category: '{cat}' }},")
        lines.append("  },")
    lines.append("};")
    lines.append("")

    # Button tables (just mode IDs — names derived from MODE_TABLES)
    lines.append("export const BTN_IDS: Record<VehicleType, number[]> = {")
    for vtype, _, _, _, btns in VEHICLE_DEFS:
        ids = [str(b[0]) for b in btns]
        lines.append(f"  {vtype}: [{', '.join(ids)}],")
    lines.append("};")
    lines.append("")

    # MAV_TYPE → VehicleType mapping
    lines.append("const _VTYPE_MAP: Record<number, VehicleType> = {")
    copter_types = [2, 3, 4, 13, 14]
    plane_types = [1, 19, 20, 21, 22, 23, 24, 25]
    for t in copter_types:
        lines.append(f"  {t}: 'copter',")
    for t in plane_types:
        lines.append(f"  {t}: 'plane',")
    lines.append("  10: 'rover',")
    lines.append("  12: 'sub',")
    lines.append("};")
    lines.append("")

    # Helper functions
    lines.append("export function vehicleType(mavTypeRaw: number): VehicleType {")
    lines.append("  return _VTYPE_MAP[mavTypeRaw] ?? 'copter';")
    lines.append("}")
    lines.append("")
    lines.append("export function getModeName(vtype: VehicleType, modeId: number, locale: 'en' | 'zh' = 'en'): string {")
    lines.append("  return MODE_TABLES[vtype]?.[modeId]?.[locale] ?? `MODE${modeId}`;")
    lines.append("}")
    lines.append("")
    lines.append("export function getModeCategory(vtype: VehicleType, modeId: number): ModeCategory {")
    lines.append("  return MODE_TABLES[vtype]?.[modeId]?.category ?? 'assisted';")
    lines.append("}")
    lines.append("")
    lines.append("export function getModeButtons(vtype: VehicleType, locale: 'en' | 'zh' = 'en'): [number, string][] {")
    lines.append("  const ids = BTN_IDS[vtype] ?? [];")
    lines.append("  return ids.map((id) => [id, getModeName(vtype, id, locale)]);")
    lines.append("}")
    lines.append("")
    lines.append("export function getAllModes(vtype: VehicleType): { id: number; name: string; category: ModeCategory }[] {")
    lines.append("  const table = MODE_TABLES[vtype] ?? {};")
    lines.append("  return Object.entries(table)")
    lines.append("    .map(([id, m]) => ({ id: Number(id), name: m.en, category: m.category }))")
    lines.append("    .sort((a, b) => a.id - b.id);")
    lines.append("}")
    lines.append("")
    lines.append("export function getModeEntries(vtype: VehicleType): [number, string][] {")
    lines.append("  const table = MODE_TABLES[vtype] ?? {};")
    lines.append("  return Object.entries(table)")
    lines.append("    .map(([id, m]) => [Number(id), m.en] as [number, string])")
    lines.append("    .sort((a, b) => a[0] - b[0]);")
    lines.append("}")
    lines.append("")

    return "\n".join(lines) + "\n"


def main() -> None:
    content = generate()
    OUT.write_text(content, encoding="utf-8")
    print(f"Generated {OUT.relative_to(ROOT)} ({len(content)} bytes)")


if __name__ == "__main__":
    main()
